image:
  repository: registry1.dso.mil/ironbank/sonarsource/sonarqube/sonarqube
  tag: 9.9.5-community

initContainers:
  image: registry1.dso.mil/ironbank/big-bang/base:2.1.0

prometheusExporter:
  # renovate: image=amazon/aws-cli
  image: registry1.dso.mil/ironbank/big-bang/base:2.18.10
