apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: sonarqube
  namespace: {{ .Release.Namespace }}
spec:
  network:
    expose:
      - service: sonarqube-sonarqube
        podLabels:
          app: sonarqube
        gateway: tenant
        host: sonarqube
        port: 9000
    allow:
      # Todo: wide open for hitting in-cluster or external postgres
      - direction: Egress
        podLabels:
          app: sonarqube
        remoteGenerated: Anywhere