includes:
  - create: https://raw.githubusercontent.com/defenseunicorns/uds-common-tasks/v0.1.0/tasks/create.yaml

variables:
  - name: FLAVOR
    default: "registry1"

tasks:
  - name: sonarqube-test-bundle
    description: Create the UDS bundle with Sonarqube and its dependencies
    actions:
      - task: create:package
      - task: dependency-package
      - task: create:test-bundle

  - name: sonarqube-package
    description: Create the UDS Sonarqube Zarf Package
    actions:
      - task: create:package

  - name: dependency-package
    description: Create the Dependency Zarf Package(s)
    actions:
      - cmd: zarf package create src/dev-secrets/ --confirm --no-progress --architecture=${UDS_ARCH} --skip-sbom
